version: '3.8'

services:
  db:
    container_name: "mongo"
    image: mongo:latest
    volumes:
      - mongo:/var/lib/mongo/data
    ports:
      - 27017:27017
    env_file:
      - .env

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mongo: